### ISSUE TITLE
Does not run in Xcode 7

### ISSUE THREAD

**Issue by LeonardBonfils** [stakes/JSSAlertView#20] opened 2015-08-20 18:55 UTC
Hey, nice library.
I'm getting 9 build errors on Xcode 7 (some of them are fixed automatically by Xcode, others are not):

Attached are pictures of the errors I am getting. As a beginner iOS developer, I can only fix so many errors :S
![screen shot 2015-08-20 at 2 53 19 pm](https://cloud.githubusercontent.com/assets/6782987/9392545/744cee54-474b-11e5-9ecb-e26204c8bb28.png)
![screen shot 2015-08-20 at 2 53 30 pm](https://cloud.githubusercontent.com/assets/6782987/9392544/744b24ca-474b-11e5-921d-7eb236e21be5.png)
![screen shot 2015-08-20 at 2 53 45 pm](https://cloud.githubusercontent.com/assets/6782987/9392548/74517046-474b-11e5-819e-fc2e21b2b98e.png)
![screen shot 2015-08-20 at 2 53 52 pm](https://cloud.githubusercontent.com/assets/6782987/9392546/744e0b36-474b-11e5-90e4-3c9d82db944c.png)
![screen shot 2015-08-20 at 2 54 18 pm](https://cloud.githubusercontent.com/assets/6782987/9392547/744f6198-474b-11e5-827c-e07ec5a78893.png)

**Comment by AdamHWeiss2017** [comment] 2015-08-27 04:39
Beginner iOS dev here too....but the fix is easy

Edit > Convert > To Latest Swift Syntax

Explanation of fixes:
1. All of the "Missing..." errors -- caused by missing "amount" parameter name in front of second parameter (your last picture is caused by a weird bug in Xcode where it inserts the correct parameter name in the wrong position)
2. "Cannot invoke..." error -- caused because the call for boundingRectWithSize does not take an attributes parameter of String:AnyObject? but instead String:AnyObject (optional vs. forced unwrap) so fixed by adding "!" to the end of the textAttr definition
3. Both the "overload" and "ambiguous" errors are caused by the nil value for the options parameter -- fixed by changing nil to an empty array

**Comment by swangy** [comment] 2015-09-03 16:27
for the boundingRectWithSize error in Xcode 7, beta version 7A192o i couldnt get it to downcast at that line so i had to downcast at the declaration of textAttr, line 189:

let textAttr = [NSFontAttributeName:textView.font as! AnyObject]

**Comment by alexliubj** [comment] 2015-09-11 13:33
Try my pull request to resolve this issue : https://github.com/stakes/JSSAlertView/pull/21

**Comment by syky27** [comment] 2016-03-31 11:31
Fixed by #26

**Closed by syky27** 2016-03-31 11:31 UTC
